import { Rect } from '@/types/rectangle';

export const SAMPLE_IMAGES = [
  '/sample-lemon-squeezy.jpeg',
  '/sample-zoom-call.jpeg',
  '/sample-medical-report.jpeg',
] as const;
export type SampleImage = (typeof SAMPLE_IMAGES)[number];

export const sampleImageSize: Record<SampleImage, { width: number; height: number }> = {
  '/sample-lemon-squeezy.jpeg': { width: 521, height: 640 },
  '/sample-zoom-call.jpeg': { width: 1600, height: 1000 },
  '/sample-medical-report.jpeg': { width: 760, height: 979 },
};

export const sampleImageThumbnail: Record<SampleImage, string> = {
  '/sample-lemon-squeezy.jpeg': '/sample-lemon-squeezy-thumbnail.jpg',
  '/sample-zoom-call.jpeg': '/sample-zoom-call-thumbnail.jpg',
  '/sample-medical-report.jpeg': '/sample-medical-report-thumbnail.jpg',
};

export const sampleImageRects: Record<SampleImage, Rect[]> = {
  '/sample-lemon-squeezy.jpeg': [
    {
      id: '1',
      description: 'Woohoo',
      x: 40,
      y: 113,
      width: 100,
      height: 19,
      sensitive: false,
      source: 'server',
    },
    {
      id: '2',
      description: '!',
      x: 142,
      y: 113,
      width: 8,
      height: 19,
      sensitive: false,
      source: 'server',
    },
    {
      id: '3',
      description: 'You',
      x: 156,
      y: 113,
      width: 45,
      height: 19,
      sensitive: false,
      source: 'server',
    },
    {
      id: '4',
      description: 'made',
      x: 210,
      y: 113,
      width: 67,
      height: 19,
      sensitive: false,
      source: 'server',
    },
    {
      id: '5',
      description: 'a',
      x: 285,
      y: 113,
      width: 12,
      height: 19,
      sensitive: false,
      source: 'server',
    },
    {
      id: '6',
      description: 'sale',
      x: 306,
      y: 113,
      width: 48,
      height: 19,
      sensitive: false,
      source: 'server',
    },
    {
      id: '7',
      description: '!',
      x: 355,
      y: 113,
      width: 8,
      height: 19,
      sensitive: false,
      source: 'server',
    },
    {
      id: '8',
      description: 'Order',
      x: 41,
      y: 497,
      width: 46,
      height: 14,
      sensitive: false,
      source: 'server',
    },
    {
      id: '9',
      description: '#',
      x: 91,
      y: 497,
      width: 10,
      height: 14,
      sensitive: false,
      source: 'server',
    },
    {
      id: '10',
      description: ':',
      x: 103,
      y: 497,
      width: 5,
      height: 14,
      sensitive: false,
      source: 'server',
    },
    {
      id: '11',
      description: '111589130',
      x: 113,
      y: 497,
      width: 80,
      height: 14,
      sensitive: false,
      source: 'server',
    },
    {
      id: '12',
      description: 'Date',
      x: 41,
      y: 531,
      width: 38,
      height: 14,
      sensitive: false,
      source: 'server',
    },
    {
      id: '13',
      description: ':',
      x: 78,
      y: 531,
      width: 5,
      height: 14,
      sensitive: false,
      source: 'server',
    },
    {
      id: '14',
      description: '24',
      x: 88,
      y: 531,
      width: 20,
      height: 14,
      sensitive: false,
      source: 'server',
    },
    {
      id: '15',
      description: 'Jan',
      x: 114,
      y: 531,
      width: 29,
      height: 14,
      sensitive: false,
      source: 'server',
    },
    {
      id: '16',
      description: '2025',
      x: 149,
      y: 531,
      width: 40,
      height: 14,
      sensitive: false,
      source: 'server',
    },
    {
      id: '17',
      description: ',',
      x: 189,
      y: 531,
      width: 5,
      height: 14,
      sensitive: false,
      source: 'server',
    },
    {
      id: '18',
      description: '21:33',
      x: 198,
      y: 531,
      width: 44,
      height: 14,
      sensitive: false,
      source: 'server',
    },
    {
      id: '19',
      description: 'Name',
      x: 41,
      y: 565,
      width: 47,
      height: 13,
      sensitive: false,
      source: 'server',
    },
    {
      id: '20',
      description: ':',
      x: 89,
      y: 565,
      width: 6,
      height: 13,
      sensitive: false,
      source: 'server',
    },
    {
      id: '21',
      description: 'John',
      x: 98,
      y: 565,
      width: 41,
      height: 13,
      sensitive: true,
      source: 'server',
    },
    {
      id: '22',
      description: 'Doe',
      x: 145,
      y: 565,
      width: 36,
      height: 13,
      sensitive: true,
      source: 'server',
    },
    {
      id: '23',
      description: 'Email',
      x: 41,
      y: 597,
      width: 42,
      height: 17,
      sensitive: false,
      source: 'server',
    },
    {
      id: '24',
      description: ':',
      x: 85,
      y: 597,
      width: 4,
      height: 16,
      sensitive: false,
      source: 'server',
    },
    {
      id: '25',
      description: 'johndoe@gmail.com',
      x: 94,
      y: 597,
      width: 174,
      height: 16,
      sensitive: true,
      source: 'server',
    },
  ],
  '/sample-zoom-call.jpeg': [
    {
      id: '1',
      source: 'server',
      description: 'Zoom',
      x: 781,
      y: 87,
      width: 37,
      height: 9,
      sensitive: false,
    },
    {
      id: '2',
      source: 'server',
      description: 'April',
      x: 325,
      y: 200,
      width: 28,
      height: 13,
      sensitive: true,
    },
    {
      id: '3',
      source: 'server',
      description: 'Williams',
      x: 357,
      y: 200,
      width: 53,
      height: 12,
      sensitive: true,
    },
    {
      id: '4',
      source: 'server',
      description: 'Tori',
      x: 519,
      y: 201,
      width: 23,
      height: 12,
      sensitive: true,
    },
    {
      id: '5',
      source: 'server',
      description: 'Kojuro',
      x: 547,
      y: 201,
      width: 38,
      height: 13,
      sensitive: true,
    },
    {
      id: '6',
      source: 'server',
      description: 'Madrid',
      x: 728,
      y: 197,
      width: 45,
      height: 16,
      sensitive: true,
    },
    {
      id: '7',
      source: 'server',
      description: '(',
      x: 776,
      y: 200,
      width: 5,
      height: 13,
      sensitive: false,
    },
    {
      id: '8',
      source: 'server',
      description: '5',
      x: 781,
      y: 200,
      width: 9,
      height: 13,
      sensitive: false,
    },
    {
      id: '9',
      source: 'server',
      description: ')',
      x: 788,
      y: 201,
      width: 6,
      height: 13,
      sensitive: false,
    },
    {
      id: '10',
      source: 'server',
      description: 'Casey',
      x: 905,
      y: 201,
      width: 39,
      height: 13,
      sensitive: true,
    },
    {
      id: '11',
      source: 'server',
      description: 'Cunningham',
      x: 948,
      y: 201,
      width: 79,
      height: 13,
      sensitive: true,
    },
    {
      id: '12',
      source: 'server',
      description: 'Mike',
      x: 1115,
      y: 200,
      width: 27,
      height: 12,
      sensitive: true,
    },
    {
      id: '13',
      source: 'server',
      description: 'Nolan',
      x: 1147,
      y: 200,
      width: 35,
      height: 11,
      sensitive: true,
    },
    {
      id: '14',
      source: 'server',
      description: '↑',
      x: 794,
      y: 879,
      width: 11,
      height: 9,
      sensitive: false,
    },
    {
      id: '15',
      source: 'server',
      description: 'End',
      x: 1362,
      y: 889,
      width: 24,
      height: 10,
      sensitive: false,
    },
    {
      id: '16',
      source: 'server',
      description: 'Mute',
      x: 213,
      y: 905,
      width: 31,
      height: 9,
      sensitive: false,
    },
    {
      id: '17',
      source: 'server',
      description: 'Stop',
      x: 296,
      y: 904,
      width: 30,
      height: 12,
      sensitive: false,
    },
    {
      id: '18',
      source: 'server',
      description: 'Video',
      x: 329,
      y: 903,
      width: 37,
      height: 12,
      sensitive: false,
    },
    {
      id: '19',
      source: 'server',
      description: 'Security',
      x: 569,
      y: 905,
      width: 54,
      height: 12,
      sensitive: false,
    },
    {
      id: '20',
      source: 'server',
      description: 'Participants',
      x: 655,
      y: 905,
      width: 77,
      height: 11,
      sensitive: false,
    },
    {
      id: '21',
      source: 'server',
      description: 'Share',
      x: 757,
      y: 903,
      width: 37,
      height: 12,
      sensitive: false,
    },
    {
      id: '22',
      source: 'server',
      description: 'Screen',
      x: 797,
      y: 902,
      width: 44,
      height: 11,
      sensitive: false,
    },
    {
      id: '23',
      source: 'server',
      description: 'Chat',
      x: 883,
      y: 905,
      width: 30,
      height: 9,
      sensitive: false,
    },
    {
      id: '24',
      source: 'server',
      description: 'Record',
      x: 965,
      y: 905,
      width: 43,
      height: 10,
      sensitive: false,
    },
    {
      id: '25',
      source: 'server',
      description: 'Reactions',
      x: 1045,
      y: 905,
      width: 63,
      height: 10,
      sensitive: false,
    },
  ],
  '/sample-medical-report.jpeg': [
    {
      id: '1',
      source: 'server',
      description: 'Visit',
      x: 108,
      y: 191,
      width: 36,
      height: 13,
      sensitive: false,
    },
    {
      id: '2',
      source: 'server',
      description: 'Info',
      x: 147,
      y: 191,
      width: 30,
      height: 13,
      sensitive: false,
    },
    {
      id: '3',
      source: 'server',
      description: 'Evergreen',
      x: 199,
      y: 70,
      width: 122,
      height: 22,
      sensitive: false,
    },
    {
      id: '4',
      source: 'server',
      description: 'Wellness',
      x: 328,
      y: 70,
      width: 109,
      height: 22,
      sensitive: false,
    },
    {
      id: '5',
      source: 'server',
      description: 'Hospital',
      x: 444,
      y: 70,
      width: 99,
      height: 22,
      sensitive: false,
    },
    {
      id: '6',
      source: 'server',
      description: '123',
      x: 253,
      y: 97,
      width: 18,
      height: 12,
      sensitive: true,
    },
    {
      id: '7',
      source: 'server',
      description: 'Harmony',
      x: 273,
      y: 97,
      width: 49,
      height: 11,
      sensitive: true,
    },
    {
      id: '8',
      source: 'server',
      description: 'Street',
      x: 322,
      y: 97,
      width: 33,
      height: 11,
      sensitive: true,
    },
    {
      id: '9',
      source: 'server',
      description: 'Sunnyville',
      x: 356,
      y: 97,
      width: 54,
      height: 11,
      sensitive: true,
    },
    {
      id: '10',
      source: 'server',
      description: ',',
      x: 409,
      y: 97,
      width: 3,
      height: 11,
      sensitive: false,
    },
    {
      id: '11',
      source: 'server',
      description: 'CA',
      x: 415,
      y: 97,
      width: 15,
      height: 11,
      sensitive: true,
    },
    {
      id: '12',
      source: 'server',
      description: '90210',
      x: 432,
      y: 97,
      width: 33,
      height: 11,
      sensitive: true,
    },
    {
      id: '13',
      source: 'server',
      description: 'USA',
      x: 468,
      y: 97,
      width: 21,
      height: 11,
      sensitive: true,
    },
    {
      id: '14',
      source: 'server',
      description: 'MEDICAL',
      x: 262,
      y: 146,
      width: 113,
      height: 19,
      sensitive: false,
    },
    {
      id: '15',
      source: 'server',
      description: 'REPORT',
      x: 382,
      y: 146,
      width: 98,
      height: 19,
      sensitive: false,
    },
    {
      id: '16',
      source: 'server',
      description: "Doctor's",
      x: 109,
      y: 223,
      width: 55,
      height: 13,
      sensitive: false,
    },
    {
      id: '17',
      source: 'server',
      description: 'Name',
      x: 167,
      y: 223,
      width: 40,
      height: 12,
      sensitive: false,
    },
    {
      id: '18',
      source: 'server',
      description: ':',
      x: 207,
      y: 223,
      width: 5,
      height: 12,
      sensitive: false,
    },
    {
      id: '19',
      source: 'server',
      description: 'Dr.',
      x: 231,
      y: 223,
      width: 17,
      height: 12,
      sensitive: true,
    },
    {
      id: '20',
      source: 'server',
      description: 'Olivia',
      x: 253,
      y: 222,
      width: 35,
      height: 13,
      sensitive: true,
    },
    {
      id: '21',
      source: 'server',
      description: 'Greene',
      x: 291,
      y: 222,
      width: 50,
      height: 12,
      sensitive: true,
    },
    {
      id: '22',
      source: 'server',
      description: 'Visit',
      x: 418,
      y: 224,
      width: 30,
      height: 11,
      sensitive: false,
    },
    {
      id: '23',
      source: 'server',
      description: 'Date',
      x: 452,
      y: 224,
      width: 31,
      height: 11,
      sensitive: false,
    },
    {
      id: '24',
      source: 'server',
      description: ':',
      x: 483,
      y: 224,
      width: 4,
      height: 11,
      sensitive: false,
    },
    {
      id: '25',
      source: 'server',
      description: '14.11.2023',
      x: 500,
      y: 224,
      width: 72,
      height: 11,
      sensitive: false,
    },
    {
      id: '26',
      source: 'server',
      description: 'Specialization',
      x: 109,
      y: 254,
      width: 91,
      height: 13,
      sensitive: false,
    },
    {
      id: '27',
      source: 'server',
      description: ':',
      x: 201,
      y: 254,
      width: 5,
      height: 13,
      sensitive: false,
    },
    {
      id: '28',
      source: 'server',
      description: 'Cardiology',
      x: 231,
      y: 253,
      width: 70,
      height: 13,
      sensitive: false,
    },
    {
      id: '29',
      source: 'server',
      description: 'Patient',
      x: 109,
      y: 317,
      width: 55,
      height: 13,
      sensitive: false,
    },
    {
      id: '30',
      source: 'server',
      description: 'Info',
      x: 168,
      y: 317,
      width: 30,
      height: 13,
      sensitive: false,
    },
    {
      id: '31',
      source: 'server',
      description: 'Full',
      x: 109,
      y: 350,
      width: 25,
      height: 11,
      sensitive: false,
    },
    {
      id: '32',
      source: 'server',
      description: 'Name',
      x: 137,
      y: 350,
      width: 40,
      height: 11,
      sensitive: false,
    },
    {
      id: '33',
      source: 'server',
      description: ':',
      x: 177,
      y: 350,
      width: 5,
      height: 11,
      sensitive: false,
    },
    {
      id: '34',
      source: 'server',
      description: 'Sarah',
      x: 231,
      y: 349,
      width: 36,
      height: 12,
      sensitive: true,
    },
    {
      id: '35',
      source: 'server',
      description: 'Anderson',
      x: 269,
      y: 349,
      width: 64,
      height: 11,
      sensitive: true,
    },
    {
      id: '36',
      source: 'server',
      description: 'Birth',
      x: 415,
      y: 349,
      width: 31,
      height: 13,
      sensitive: false,
    },
    {
      id: '37',
      source: 'server',
      description: 'Date',
      x: 451,
      y: 349,
      width: 31,
      height: 12,
      sensitive: false,
    },
    {
      id: '38',
      source: 'server',
      description: ':',
      x: 482,
      y: 349,
      width: 5,
      height: 12,
      sensitive: false,
    },
    {
      id: '39',
      source: 'server',
      description: '01.01.1989',
      x: 499,
      y: 348,
      width: 72,
      height: 12,
      sensitive: true,
    },
    {
      id: '40',
      source: 'server',
      description: 'Med',
      x: 109,
      y: 380,
      width: 31,
      height: 12,
      sensitive: false,
    },
    {
      id: '41',
      source: 'server',
      description: '.',
      x: 140,
      y: 380,
      width: 4,
      height: 12,
      sensitive: false,
    },
    {
      id: '42',
      source: 'server',
      description: 'Number',
      x: 148,
      y: 380,
      width: 56,
      height: 12,
      sensitive: false,
    },
    {
      id: '43',
      source: 'server',
      description: ':',
      x: 203,
      y: 380,
      width: 5,
      height: 12,
      sensitive: false,
    },
    {
      id: '44',
      source: 'server',
      description: 'MA567891',
      x: 232,
      y: 380,
      width: 70,
      height: 11,
      sensitive: true,
    },
    {
      id: '45',
      source: 'server',
      description: 'Phone',
      x: 109,
      y: 409,
      width: 42,
      height: 11,
      sensitive: false,
    },
    {
      id: '46',
      source: 'server',
      description: ':',
      x: 152,
      y: 409,
      width: 5,
      height: 11,
      sensitive: false,
    },
    {
      id: '47',
      source: 'server',
      description: '+1',
      x: 231,
      y: 408,
      width: 16,
      height: 15,
      sensitive: true,
    },
    {
      id: '48',
      source: 'server',
      description: '(',
      x: 250,
      y: 408,
      width: 4,
      height: 14,
      sensitive: false,
    },
    {
      id: '49',
      source: 'server',
      description: '555',
      x: 255,
      y: 408,
      width: 24,
      height: 14,
      sensitive: true,
    },
    {
      id: '50',
      source: 'server',
      description: ')',
      x: 279,
      y: 408,
      width: 5,
      height: 14,
      sensitive: false,
    },
    {
      id: '51',
      source: 'server',
      description: '789-0123',
      x: 288,
      y: 408,
      width: 61,
      height: 14,
      sensitive: true,
    },
    {
      id: '52',
      source: 'server',
      description: 'IHI',
      x: 465,
      y: 380,
      width: 17,
      height: 12,
      sensitive: false,
    },
    {
      id: '53',
      source: 'server',
      description: ':',
      x: 483,
      y: 380,
      width: 5,
      height: 12,
      sensitive: false,
    },
    {
      id: '54',
      source: 'server',
      description: '5556-9669-9654-7788',
      x: 499,
      y: 380,
      width: 146,
      height: 12,
      sensitive: true,
    },
    {
      id: '55',
      source: 'server',
      description: 'Email',
      x: 446,
      y: 409,
      width: 37,
      height: 14,
      sensitive: false,
    },
    {
      id: '56',
      source: 'server',
      description: ':',
      x: 484,
      y: 409,
      width: 5,
      height: 14,
      sensitive: false,
    },
    {
      id: '57',
      source: 'server',
      description: 's.anderson@mail.com',
      x: 500,
      y: 409,
      width: 144,
      height: 14,
      sensitive: true,
    },
    {
      id: '58',
      source: 'server',
      description: 'Assessment',
      x: 108,
      y: 473,
      width: 90,
      height: 12,
      sensitive: false,
    },
    {
      id: '59',
      source: 'server',
      description: 'Ms.',
      x: 109,
      y: 505,
      width: 21,
      height: 12,
      sensitive: false,
    },
    {
      id: '60',
      source: 'server',
      description: 'Anderson',
      x: 132,
      y: 505,
      width: 55,
      height: 12,
      sensitive: true,
    },
    {
      id: '61',
      source: 'server',
      description: 'appears',
      x: 190,
      y: 505,
      width: 44,
      height: 12,
      sensitive: false,
    },
    {
      id: '62',
      source: 'server',
      description: 'in',
      x: 237,
      y: 505,
      width: 10,
      height: 12,
      sensitive: false,
    },
    {
      id: '63',
      source: 'server',
      description: 'good',
      x: 251,
      y: 505,
      width: 27,
      height: 12,
      sensitive: false,
    },
    {
      id: '64',
      source: 'server',
      description: 'health',
      x: 283,
      y: 505,
      width: 34,
      height: 12,
      sensitive: false,
    },
    {
      id: '65',
      source: 'server',
      description: 'with',
      x: 321,
      y: 505,
      width: 24,
      height: 12,
      sensitive: false,
    },
    {
      id: '66',
      source: 'server',
      description: 'no',
      x: 349,
      y: 505,
      width: 14,
      height: 12,
      sensitive: false,
    },
    {
      id: '67',
      source: 'server',
      description: 'immediate',
      x: 366,
      y: 505,
      width: 61,
      height: 12,
      sensitive: false,
    },
    {
      id: '68',
      source: 'server',
      description: 'concerns',
      x: 430,
      y: 505,
      width: 50,
      height: 12,
      sensitive: false,
    },
    {
      id: '69',
      source: 'server',
      description: 'during',
      x: 483,
      y: 505,
      width: 37,
      height: 12,
      sensitive: false,
    },
    {
      id: '70',
      source: 'server',
      description: 'the',
      x: 522,
      y: 505,
      width: 19,
      height: 12,
      sensitive: false,
    },
    {
      id: '71',
      source: 'server',
      description: 'examination',
      x: 544,
      y: 505,
      width: 69,
      height: 12,
      sensitive: false,
    },
    {
      id: '72',
      source: 'server',
      description: '.',
      x: 613,
      y: 505,
      width: 4,
      height: 12,
      sensitive: false,
    },
    {
      id: '73',
      source: 'server',
      description: 'Based',
      x: 109,
      y: 530,
      width: 33,
      height: 12,
      sensitive: false,
    },
    {
      id: '74',
      source: 'server',
      description: 'on',
      x: 146,
      y: 530,
      width: 14,
      height: 12,
      sensitive: false,
    },
    {
      id: '75',
      source: 'server',
      description: 'the',
      x: 163,
      y: 530,
      width: 19,
      height: 12,
      sensitive: false,
    },
    {
      id: '76',
      source: 'server',
      description: 'assessment',
      x: 185,
      y: 530,
      width: 65,
      height: 12,
      sensitive: false,
    },
    {
      id: '77',
      source: 'server',
      description: ',',
      x: 249,
      y: 530,
      width: 4,
      height: 12,
      sensitive: false,
    },
    {
      id: '78',
      source: 'server',
      description: 'there',
      x: 256,
      y: 530,
      width: 32,
      height: 12,
      sensitive: false,
    },
    {
      id: '79',
      source: 'server',
      description: 'are',
      x: 290,
      y: 530,
      width: 18,
      height: 12,
      sensitive: false,
    },
    {
      id: '80',
      source: 'server',
      description: 'no',
      x: 311,
      y: 530,
      width: 14,
      height: 12,
      sensitive: false,
    },
    {
      id: '81',
      source: 'server',
      description: 'significant',
      x: 329,
      y: 530,
      width: 57,
      height: 12,
      sensitive: false,
    },
    {
      id: '82',
      source: 'server',
      description: 'issues',
      x: 388,
      y: 530,
      width: 35,
      height: 12,
      sensitive: false,
    },
    {
      id: '83',
      source: 'server',
      description: 'detected',
      x: 425,
      y: 530,
      width: 49,
      height: 12,
      sensitive: false,
    },
    {
      id: '84',
      source: 'server',
      description: ',',
      x: 475,
      y: 530,
      width: 4,
      height: 12,
      sensitive: false,
    },
    {
      id: '85',
      source: 'server',
      description: 'and',
      x: 481,
      y: 530,
      width: 21,
      height: 12,
      sensitive: false,
    },
    {
      id: '86',
      source: 'server',
      description: 'vital',
      x: 505,
      y: 530,
      width: 24,
      height: 12,
      sensitive: false,
    },
    {
      id: '87',
      source: 'server',
      description: 'signs',
      x: 533,
      y: 530,
      width: 27,
      height: 12,
      sensitive: false,
    },
    {
      id: '88',
      source: 'server',
      description: 'are',
      x: 563,
      y: 530,
      width: 19,
      height: 12,
      sensitive: false,
    },
    {
      id: '89',
      source: 'server',
      description: 'within',
      x: 585,
      y: 530,
      width: 35,
      height: 12,
      sensitive: false,
    },
    {
      id: '90',
      source: 'server',
      description: 'normal',
      x: 109,
      y: 555,
      width: 40,
      height: 11,
      sensitive: false,
    },
    {
      id: '91',
      source: 'server',
      description: 'ranges',
      x: 153,
      y: 555,
      width: 37,
      height: 11,
      sensitive: false,
    },
    {
      id: '92',
      source: 'server',
      description: '.',
      x: 189,
      y: 555,
      width: 4,
      height: 11,
      sensitive: false,
    },
    {
      id: '93',
      source: 'server',
      description: 'Diagnosis',
      x: 109,
      y: 582,
      width: 73,
      height: 14,
      sensitive: false,
    },
    {
      id: '94',
      source: 'server',
      description: 'After',
      x: 108,
      y: 613,
      width: 30,
      height: 13,
      sensitive: false,
    },
    {
      id: '95',
      source: 'server',
      description: 'thorough',
      x: 140,
      y: 613,
      width: 51,
      height: 13,
      sensitive: false,
    },
    {
      id: '96',
      source: 'server',
      description: 'examination',
      x: 195,
      y: 613,
      width: 69,
      height: 13,
      sensitive: false,
    },
    {
      id: '97',
      source: 'server',
      description: ',',
      x: 264,
      y: 613,
      width: 4,
      height: 13,
      sensitive: false,
    },
    {
      id: '98',
      source: 'server',
      description: 'no',
      x: 271,
      y: 613,
      width: 14,
      height: 13,
      sensitive: false,
    },
    {
      id: '99',
      source: 'server',
      description: 'specific',
      x: 288,
      y: 613,
      width: 43,
      height: 13,
      sensitive: false,
    },
    {
      id: '100',
      source: 'server',
      description: 'medical',
      x: 334,
      y: 613,
      width: 43,
      height: 13,
      sensitive: false,
    },
    {
      id: '101',
      source: 'server',
      description: 'conditions',
      x: 380,
      y: 613,
      width: 58,
      height: 13,
      sensitive: false,
    },
    {
      id: '102',
      source: 'server',
      description: 'or',
      x: 441,
      y: 613,
      width: 13,
      height: 13,
      sensitive: false,
    },
    {
      id: '103',
      source: 'server',
      description: 'acute',
      x: 457,
      y: 613,
      width: 31,
      height: 13,
      sensitive: false,
    },
    {
      id: '104',
      source: 'server',
      description: 'illnesses',
      x: 490,
      y: 613,
      width: 48,
      height: 13,
      sensitive: false,
    },
    {
      id: '105',
      source: 'server',
      description: 'were',
      x: 539,
      y: 613,
      width: 30,
      height: 13,
      sensitive: false,
    },
    {
      id: '106',
      source: 'server',
      description: 'identified',
      x: 572,
      y: 613,
      width: 53,
      height: 13,
      sensitive: false,
    },
    {
      id: '107',
      source: 'server',
      description: '.',
      x: 625,
      y: 613,
      width: 3,
      height: 13,
      sensitive: false,
    },
    {
      id: '108',
      source: 'server',
      description: 'The',
      x: 108,
      y: 638,
      width: 23,
      height: 12,
      sensitive: false,
    },
    {
      id: '109',
      source: 'server',
      description: 'diagnosis',
      x: 133,
      y: 638,
      width: 52,
      height: 12,
      sensitive: false,
    },
    {
      id: '110',
      source: 'server',
      description: 'indicates',
      x: 188,
      y: 638,
      width: 50,
      height: 12,
      sensitive: false,
    },
    {
      id: '111',
      source: 'server',
      description: 'a',
      x: 241,
      y: 638,
      width: 6,
      height: 12,
      sensitive: false,
    },
    {
      id: '112',
      source: 'server',
      description: 'healthy',
      x: 251,
      y: 638,
      width: 42,
      height: 12,
      sensitive: false,
    },
    {
      id: '113',
      source: 'server',
      description: 'status',
      x: 295,
      y: 638,
      width: 33,
      height: 12,
      sensitive: false,
    },
    {
      id: '114',
      source: 'server',
      description: 'with',
      x: 332,
      y: 638,
      width: 25,
      height: 12,
      sensitive: false,
    },
    {
      id: '115',
      source: 'server',
      description: 'no',
      x: 360,
      y: 638,
      width: 14,
      height: 12,
      sensitive: false,
    },
    {
      id: '116',
      source: 'server',
      description: 'evidence',
      x: 378,
      y: 638,
      width: 50,
      height: 12,
      sensitive: false,
    },
    {
      id: '117',
      source: 'server',
      description: 'of',
      x: 431,
      y: 638,
      width: 13,
      height: 12,
      sensitive: false,
    },
    {
      id: '118',
      source: 'server',
      description: 'underlying',
      x: 446,
      y: 638,
      width: 59,
      height: 12,
      sensitive: false,
    },
    {
      id: '119',
      source: 'server',
      description: 'health',
      x: 509,
      y: 638,
      width: 35,
      height: 12,
      sensitive: false,
    },
    {
      id: '120',
      source: 'server',
      description: 'issues',
      x: 547,
      y: 638,
      width: 34,
      height: 12,
      sensitive: false,
    },
    {
      id: '121',
      source: 'server',
      description: '.',
      x: 581,
      y: 638,
      width: 3,
      height: 12,
      sensitive: false,
    },
    {
      id: '122',
      source: 'server',
      description: 'Prescription',
      x: 109,
      y: 666,
      width: 92,
      height: 14,
      sensitive: false,
    },
    {
      id: '123',
      source: 'server',
      description: 'No',
      x: 109,
      y: 697,
      width: 17,
      height: 12,
      sensitive: false,
    },
    {
      id: '124',
      source: 'server',
      description: 'prescription',
      x: 128,
      y: 697,
      width: 67,
      height: 12,
      sensitive: false,
    },
    {
      id: '125',
      source: 'server',
      description: 'is',
      x: 199,
      y: 697,
      width: 8,
      height: 12,
      sensitive: false,
    },
    {
      id: '126',
      source: 'server',
      description: 'necessary',
      x: 211,
      y: 697,
      width: 55,
      height: 12,
      sensitive: false,
    },
    {
      id: '127',
      source: 'server',
      description: 'at',
      x: 269,
      y: 697,
      width: 11,
      height: 12,
      sensitive: false,
    },
    {
      id: '128',
      source: 'server',
      description: 'this',
      x: 283,
      y: 697,
      width: 20,
      height: 12,
      sensitive: false,
    },
    {
      id: '129',
      source: 'server',
      description: 'time',
      x: 306,
      y: 697,
      width: 26,
      height: 12,
      sensitive: false,
    },
    {
      id: '130',
      source: 'server',
      description: ',',
      x: 331,
      y: 697,
      width: 5,
      height: 12,
      sensitive: false,
    },
    {
      id: '131',
      source: 'server',
      description: 'as',
      x: 339,
      y: 697,
      width: 12,
      height: 12,
      sensitive: false,
    },
    {
      id: '132',
      source: 'server',
      description: 'the',
      x: 353,
      y: 697,
      width: 20,
      height: 12,
      sensitive: false,
    },
    {
      id: '133',
      source: 'server',
      description: 'patient',
      x: 376,
      y: 697,
      width: 40,
      height: 12,
      sensitive: false,
    },
    {
      id: '134',
      source: 'server',
      description: 'is',
      x: 419,
      y: 697,
      width: 8,
      height: 12,
      sensitive: false,
    },
    {
      id: '135',
      source: 'server',
      description: 'in',
      x: 430,
      y: 697,
      width: 10,
      height: 12,
      sensitive: false,
    },
    {
      id: '136',
      source: 'server',
      description: 'good',
      x: 443,
      y: 697,
      width: 29,
      height: 12,
      sensitive: false,
    },
    {
      id: '137',
      source: 'server',
      description: 'health',
      x: 475,
      y: 697,
      width: 35,
      height: 12,
      sensitive: false,
    },
    {
      id: '138',
      source: 'server',
      description: 'with',
      x: 513,
      y: 697,
      width: 25,
      height: 12,
      sensitive: false,
    },
    {
      id: '139',
      source: 'server',
      description: 'no',
      x: 542,
      y: 697,
      width: 14,
      height: 12,
      sensitive: false,
    },
    {
      id: '140',
      source: 'server',
      description: 'identified',
      x: 559,
      y: 697,
      width: 54,
      height: 12,
      sensitive: false,
    },
    {
      id: '141',
      source: 'server',
      description: 'medical',
      x: 109,
      y: 722,
      width: 45,
      height: 13,
      sensitive: false,
    },
    {
      id: '142',
      source: 'server',
      description: 'concerns',
      x: 156,
      y: 722,
      width: 51,
      height: 13,
      sensitive: false,
    },
    {
      id: '143',
      source: 'server',
      description: '.',
      x: 207,
      y: 722,
      width: 4,
      height: 13,
      sensitive: false,
    },
    {
      id: '144',
      source: 'server',
      description: 'Given',
      x: 213,
      y: 722,
      width: 31,
      height: 13,
      sensitive: false,
    },
    {
      id: '145',
      source: 'server',
      description: 'the',
      x: 247,
      y: 722,
      width: 20,
      height: 13,
      sensitive: false,
    },
    {
      id: '146',
      source: 'server',
      description: 'absence',
      x: 270,
      y: 722,
      width: 46,
      height: 13,
      sensitive: false,
    },
    {
      id: '147',
      source: 'server',
      description: 'of',
      x: 319,
      y: 722,
      width: 13,
      height: 13,
      sensitive: false,
    },
    {
      id: '148',
      source: 'server',
      description: 'any',
      x: 334,
      y: 722,
      width: 20,
      height: 13,
      sensitive: false,
    },
    {
      id: '149',
      source: 'server',
      description: 'medical',
      x: 357,
      y: 722,
      width: 43,
      height: 13,
      sensitive: false,
    },
    {
      id: '150',
      source: 'server',
      description: 'issues',
      x: 403,
      y: 722,
      width: 34,
      height: 13,
      sensitive: false,
    },
    {
      id: '151',
      source: 'server',
      description: ',',
      x: 437,
      y: 722,
      width: 4,
      height: 13,
      sensitive: false,
    },
    {
      id: '152',
      source: 'server',
      description: 'no',
      x: 444,
      y: 722,
      width: 14,
      height: 13,
      sensitive: false,
    },
    {
      id: '153',
      source: 'server',
      description: 'medication',
      x: 461,
      y: 722,
      width: 62,
      height: 13,
      sensitive: false,
    },
    {
      id: '154',
      source: 'server',
      description: 'is',
      x: 527,
      y: 722,
      width: 8,
      height: 13,
      sensitive: false,
    },
    {
      id: '155',
      source: 'server',
      description: 'prescribed',
      x: 539,
      y: 722,
      width: 58,
      height: 13,
      sensitive: false,
    },
    {
      id: '156',
      source: 'server',
      description: 'at',
      x: 601,
      y: 722,
      width: 12,
      height: 13,
      sensitive: false,
    },
    {
      id: '157',
      source: 'server',
      description: 'present',
      x: 109,
      y: 749,
      width: 43,
      height: 10,
      sensitive: false,
    },
    {
      id: '158',
      source: 'server',
      description: '.',
      x: 152,
      y: 749,
      width: 3,
      height: 10,
      sensitive: false,
    },
    {
      id: '159',
      source: 'server',
      description: 'For',
      x: 219,
      y: 904,
      width: 18,
      height: 12,
      sensitive: false,
    },
    {
      id: '160',
      source: 'server',
      description: 'inquiries',
      x: 240,
      y: 904,
      width: 48,
      height: 12,
      sensitive: false,
    },
    {
      id: '161',
      source: 'server',
      description: 'and',
      x: 291,
      y: 904,
      width: 21,
      height: 12,
      sensitive: false,
    },
    {
      id: '162',
      source: 'server',
      description: 'appointments',
      x: 316,
      y: 904,
      width: 77,
      height: 12,
      sensitive: false,
    },
    {
      id: '163',
      source: 'server',
      description: ',',
      x: 393,
      y: 904,
      width: 3,
      height: 12,
      sensitive: false,
    },
    {
      id: '164',
      source: 'server',
      description: 'feel',
      x: 399,
      y: 904,
      width: 21,
      height: 12,
      sensitive: false,
    },
    {
      id: '165',
      source: 'server',
      description: 'free',
      x: 422,
      y: 904,
      width: 23,
      height: 12,
      sensitive: false,
    },
    {
      id: '166',
      source: 'server',
      description: 'to',
      x: 447,
      y: 904,
      width: 12,
      height: 12,
      sensitive: false,
    },
    {
      id: '167',
      source: 'server',
      description: 'contact',
      x: 463,
      y: 904,
      width: 42,
      height: 12,
      sensitive: false,
    },
    {
      id: '168',
      source: 'server',
      description: 'us',
      x: 508,
      y: 904,
      width: 13,
      height: 12,
      sensitive: false,
    },
    {
      id: '169',
      source: 'server',
      description: '.',
      x: 520,
      y: 904,
      width: 3,
      height: 12,
      sensitive: false,
    },
    {
      id: '170',
      source: 'server',
      description: 'phone',
      x: 172,
      y: 921,
      width: 35,
      height: 12,
      sensitive: false,
    },
    {
      id: '171',
      source: 'server',
      description: ':',
      x: 208,
      y: 921,
      width: 3,
      height: 12,
      sensitive: false,
    },
    {
      id: '172',
      source: 'server',
      description: '+1',
      x: 215,
      y: 921,
      width: 13,
      height: 12,
      sensitive: true,
    },
    {
      id: '173',
      source: 'server',
      description: '(',
      x: 232,
      y: 921,
      width: 4,
      height: 12,
      sensitive: false,
    },
    {
      id: '174',
      source: 'server',
      description: '555',
      x: 236,
      y: 921,
      width: 21,
      height: 12,
      sensitive: true,
    },
    {
      id: '175',
      source: 'server',
      description: ')',
      x: 257,
      y: 921,
      width: 5,
      height: 12,
      sensitive: false,
    },
    {
      id: '176',
      source: 'server',
      description: '123-4567',
      x: 265,
      y: 921,
      width: 51,
      height: 12,
      sensitive: true,
    },
    {
      id: '177',
      source: 'server',
      description: ',',
      x: 316,
      y: 921,
      width: 3,
      height: 12,
      sensitive: false,
    },
    {
      id: '178',
      source: 'server',
      description: 'email',
      x: 323,
      y: 921,
      width: 29,
      height: 12,
      sensitive: false,
    },
    {
      id: '179',
      source: 'server',
      description: ':',
      x: 353,
      y: 921,
      width: 3,
      height: 12,
      sensitive: false,
    },
    {
      id: '180',
      source: 'server',
      description: 'info@EvergreenWellnessHospital.com',
      x: 360,
      y: 921,
      width: 209,
      height: 12,
      sensitive: true,
    },
    {
      id: '181',
      source: 'server',
      description: 'www.EvergreenWellnessHospital.com',
      x: 266,
      y: 938,
      width: 208,
      height: 12,
      sensitive: false,
    },
  ],
};
